name: Build, test and push container images

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '48 23 * * 6'

jobs:
  build-and-push:
    name: Build, test and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            toxenv: py27,py35,py36,py37,py38,py39,py310,pypy,pypy3
          - arch: arm64
            toxenv: py38,py39
          - arch: ppc64le
            toxenv: py37,py38
          - arch: s390x
            toxenv: py35,py36,py38,pypy3
    steps:
      - name: Checkout
        run: |
          for x in 1 2 3 4
          do 
            echo $x
         done
      - name: second try
        run: >
          for x in 1 2 3 4; do
            echo $x;
          done

